USE [master]
GO

/****** Object:  Database [RepCheck]    Script Date: 9/18/2015 4:22:12 PM ******/
CREATE DATABASE [RepCheck] ON  PRIMARY 
( NAME = N'RepCheck', FILENAME = N'F:\PP8\Databases\ProdP8_N-Z\Data\RepCheck.mdf' , SIZE = 30976KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'RepCheck_log', FILENAME = N'F:\PP8\Logs\ProdP8_N-Z\Data\RepCheck_log.ldf' , SIZE = 9216KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RepCheck] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RepCheck].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RepCheck] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RepCheck] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RepCheck] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RepCheck] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RepCheck] SET ARITHABORT OFF 
GO

ALTER DATABASE [RepCheck] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RepCheck] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RepCheck] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RepCheck] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RepCheck] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RepCheck] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RepCheck] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RepCheck] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RepCheck] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RepCheck] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RepCheck] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RepCheck] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RepCheck] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RepCheck] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RepCheck] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RepCheck] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RepCheck] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RepCheck] SET RECOVERY FULL 
GO

ALTER DATABASE [RepCheck] SET  MULTI_USER 
GO

ALTER DATABASE [RepCheck] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RepCheck] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RepCheck] SET  READ_WRITE 
GO


