Public Enum ExitCode
    SUCCESS = 0
    ERROR_INVALID_FUNCTION = 2
    ERROR_ACCESS_DENIED = 5
    ERROR_BAD_ARGUMENTS = 160
    ERROR_PROCESS_ABORTED = 1067
    ERROR_DATABASE_FAILURE = 5313
    RPC_S_CALL_FAILED = 1727
    ERROR_EVENTLOG_CANT_START = 1501
End Enum
