'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrphanedFile
    Public Property OrphanedFileID As Integer
    Public Property ReportID As Integer
    Public Property Path As String
    Public Property CreationTime As Date

    Public Overridable Property RepCheckReport As RepCheckReport

End Class
