'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RepCheckReport
    Public Property ReportID As Integer
    Public Property ReportDate As Date
    Public Property ObjectStoreName As String
    Public Property DBTime As Decimal
    Public Property FSTime As Decimal
    Public Property ProcessTime As Decimal

    Public Overridable Property MissingFiles As ICollection(Of MissingFile) = New HashSet(Of MissingFile)
    Public Overridable Property OrphanedFiles As ICollection(Of OrphanedFile) = New HashSet(Of OrphanedFile)

End Class
