'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ReportEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ReportEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property MissingFiles() As DbSet(Of MissingFile)
    Public Overridable Property OrphanedFiles() As DbSet(Of OrphanedFile)
    Public Overridable Property RepCheckReports() As DbSet(Of RepCheckReport)

End Class
